### ISSUE TITLE
字体无法使用，请求0B大小

### ISSUE THREAD

**Issue by momo54181** [54ayao/Chinajsdelivr#15]

**Comment by 54ayao** [comment]
给一个链接，我去排查一下吧 可能是网宿cdn侧没有配置好

**Comment by momo54181** [comment]
https://jsd.cdn.zzko.cn/npm/@fortawesome/fontawesome-free/webfonts/fa-regular-400.ttf

**Comment by momo54181** [comment]
![屏幕截图 2023-03-04 203923](https://user-images.githubusercontent.com/79344479/222901819-e47e014e-beef-4112-ab12-305709fb876a.jpg)

**Comment by 54ayao** [comment]
好 最后一个事情了，节点IP发我一下 看看那家cdn去

**Comment by momo54181** [comment]
eros8gfk.slt-dk.sched.tdnsv8.com [240e:928:101:500:2c::]

**Comment by momo54181** [comment]
ok了

**Comment by 54ayao** [comment]
![Screenshot_2023-03-04-20-47-40-035_com microsoft rdc androidx](https://user-images.githubusercontent.com/86733666/222902242-e118a653-e20c-47e8-8eaa-3b24812f1950.jpg)
您好，感谢您的反馈，经核实，网宿cdn是默认穿透源站头部的，导致这次原因，就是以为和腾讯一样需要配置头部，导致了冲突，在发版处理 10分钟就好了

**Comment by 54ayao** [comment]
腾讯云也有问题吗 我看看 稍等

**Comment by 54ayao** [comment]
根据头部来看的话腾讯cdn没问题
![Uploading Screenshot_2023-03-04-20-53-14-248_com.microsoft.rdc.androidx.jpg…]()

**Comment by 54ayao** [comment]
如图所示，检查了腾讯是正常的
![Screenshot_2023-03-04-20-53-14-248_com microsoft rdc androidx](https://user-images.githubusercontent.com/86733666/222903208-fa4fbe55-2663-4897-bb03-9c579f52072d.jpg
网宿侧cdn配置已下发，等待生效

**Comment by 54ayao** [comment]
![Screenshot_2023-03-04-21-02-20-831_com microsoft rdc androidx](https://user-images.githubusercontent.com/86733666/222903416-409d7339-a861-47bf-ab0b-affc03ef1a68.jpg)

**Comment by 54ayao** [comment]
![-5bcfebc6426358ea](https://user-images.githubusercontent.com/86733666/222903495-fdd54c96-936a-4226-af7f-04455ddbb512.jpg)

应该生效了

**Comment by momo54181** [comment]
访问正常

**Comment by 54ayao** [comment]
![Screenshot_2023-03-04-21-06-44-082_com microsoft rdc androidx](https://user-images.githubusercontent.com/86733666/222903581-e7374638-b127-436f-837a-4d8c026da20a.jpg)

网宿侧配置已更新完成，非常感谢你的反馈
