### ISSUE TITLE
与cdn.jsdelivr.net返回的内容不一致

### ISSUE THREAD

**Issue by xingpingcn** [54ayao/Chinajsdelivr#16]
https://jsd.cdn.zzko.cn/gh/xingpingcn/website.comments/style.css
https://cdn.jsdelivr.net/gh/xingpingcn/website.comments/style.css

下图为二者文本对比
![image](https://user-images.githubusercontent.com/117259690/233564242-1a0c6452-9936-4b4a-bd94-9ac01dab47b8.png)

似乎是因为没有指定编码
![image](https://user-images.githubusercontent.com/117259690/233564716-04d001c9-2f3e-498b-987f-a9564c119aae.png)

**Comment by xingpingcn** [comment]
https://jsd.cdn.zzko.cn/gh/xingpingcn/website.comments/style.css
之前此文件添加了@charset "UTF-8";就没有问题，现在此文件解码又出错了

**Comment by 54ayao** [comment]
好的，感谢反馈，这边来看一下

**Comment by 54ayao** [comment]
问一下分配的是广州腾讯云节点嘛

**Comment by xingpingcn** [comment]
> 问一下分配的是广州腾讯云节点嘛

ip：159.75.198.73

**Comment by 54ayao** [comment]
应该好了，您再看看

**Comment by xingpingcn** [comment]
好像可以了，就是cdn缓存有点久，刷了好一会才刷新

**Comment by 54ayao** [comment]
好的，已了解,切备用cdn是因为主站配置上出了点问题，切了备用线路cdn，前几天主服务器使用的11dev有点卡，才换的2022，等我把主服务端恢复一下，下发个配置就再切回来

**Comment by xingpingcn** [comment]
> 好的，已了解,切备用cdn是因为主站配置上出了点问题，切了备用线路cdn，前几天主服务器使用的11dev有点卡，才换的2022，等我把主服务端恢复一下，下发个配置就再切回来

你好，cdn加速图片又出问题了https://jsd.cdn.zzko.cn/gh/xingpingcn/picx-images-hosting@master/20230420/image.55d0qoox6bg0.png

**Comment by 54ayao** [comment]
![image](https://user-images.githubusercontent.com/86733666/234689172-4c8f95f4-c860-4307-b239-4c5bd832fc98.png)
目前先这样
content-type:'. $mimetype .';charset=utf-8;我再看看怎么加

**Comment by xingpingcn** [comment]
> ![image](https://user-images.githubusercontent.com/86733666/234689172-4c8f95f4-c860-4307-b239-4c5bd832fc98.png) 目前先这样 content-type:'. $mimetype .';charset=utf-8;我再看看怎么加

现在图片还是访问不了，使用https://cdn.jsdelivr.ren/就可以

**Comment by 54ayao** [comment]
前两天试过不行这个代码和quic协议冲突
![image](https://user-images.githubusercontent.com/86733666/235011429-d1d1885e-c9bd-428e-83db-9325c4c39eab.png)
晚点换cdn吧

**Comment by 54ayao** [comment]
说来也怪不带上 mimetype相关的就完全ok

**Comment by 54ayao** [comment]
![image](https://user-images.githubusercontent.com/86733666/235227621-5e604380-440c-4c41-894b-5681cca7944e.png)
