### ISSUE TITLE
请问下有流量限制吗

### ISSUE THREAD

**Issue by rrkelee** [54ayao/Chinajsdelivr#17]

**Comment by 54ayao** [comment]
1.下载在200mb/s
2.无流量无限制
3.单IP400qps

**Comment by 54ayao** [comment]
官网好像默认的是50m   别玩太多分片，上次一大堆分片跑了我3tb流量，大文件可以找我丢在境内的镜像站最高5gb大小左右吧 或者是我的境内节点大宽带网盘里

**Comment by rrkelee** [comment]
js  css 小文件，宽带峰值30m，日流量200G 左右，可以用吗

**Comment by 54ayao** [comment]
没问题，只要不违反当地法律法规就行
