### ISSUE TITLE
是否可以将其它jsdelivr镜像重定向到这个镜像？

### ISSUE THREAD

**Issue by codejiangqihan** [54ayao/Chinajsdelivr#19]
我的jsdelivr镜像使用了cloudflare作为CDN，但是这几个月cloudflare的速度明显变慢了。在5月份的时候，我看到了这个镜像，觉得不错，就把这个收藏了起来，最近发现cloudflare速度明显变慢了（毕竟我的镜像还是有一些站点在使用了，这样对这些站点肯定不好），所以就想要给这个镜像停止运营，重定向到一个速度快的镜像，正好想起来了这个镜像，我就把博客替换了这个镜像几天，速度很快，我就想要把我的镜像重定向到这个镜像，这样可以吗？（我的镜像一天有10万个请求，大约有10GB的流量）

**Comment by 54ayao** [comment]
可以的，基本上没有什么问题
