### ISSUE TITLE
ERROR 502

### ISSUE THREAD

**Issue by momo54181** [54ayao/Chinajsdelivr#20]
域名：blog.mocn.top

节点IP:27.185.201.162

时间:2023年8月10日11:44

用户省份：中国 山西

CDN: China/huaweicloud

CDN访问参数：

是否测试 jsdelivr官方源站：是/jsdelivr官方源站无该报错

使用影响： js css 无法加载

**Comment by momo54181** [comment]
![image](https://github.com/54ayao/Chinajsdelivr/assets/79344479/8b523870-a042-49b0-bd64-aebca4ba6cc0)

**Comment by momo54181** [comment]
gh库302跳转到国际站
cdn.jsdelivr.us

**Comment by 54ayao** [comment]
等一下我给你加个白 攻击到现在还没停 这边的配置 不跳国际站

**Comment by 54ayao** [comment]
npm 502目前好了 /gh不跳转的配置正在下发中。

**Comment by 54ayao** [comment]
目前应该正常了如果资源不是
momo54181
在联系我看看，异常流量停止之后我再切回来(

**Comment by momo54181** [comment]
为保证网站访问稳定，我决定自建jsd反代cdn
抱歉
