### ISSUE TITLE
貌似不支持 jsdelivr 的 ESM 版本？

### ISSUE THREAD

**Issue by jinliming2** [54ayao/Chinajsdelivr#21]
比如：https://cdn.jsdelivr.net/npm/dayjs@1/+esm

**Comment by xtz136** [comment]
https://cdn.jsdelivr.us/npm/hls.js@1.4.12/dist/hls.min.js
这个直接显示”Connection timed out“

**Comment by 54ayao** [comment]
感谢反馈
看起来源站挂了挂了一个，这边来个屏蔽
服务器监控显示
https://status.zzko.cn/
美国节点死了(
是什么业务呢 需要用到国际站?

**Comment by xtz136** [comment]
一个流量很少的影视站，只用来代理js、css，没搞分片播放😃

A Yao ***@***.***> 于 2023年9月20日周三 上午3:22写道：
