### ISSUE TITLE
cdn.jsdelivr.us的响应头有两个Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by xingpingcn** [54ayao/Chinajsdelivr#23]
![image](https://github.com/54ayao/Chinajsdelivr/assets/117259690/3e5f13ca-a739-436b-98f5-3f58f75806f5)

打开控制台会报错
Access to fetch at 'https://cdn.jsdelivr.us/gh/xingpingcn/picx-images-hosting@master/20230420/image.55d0qoox6bg0.png' from origin 'https://www.xingpingcn.top' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

如果是cdn.jsdelivr.net 就没有问题。

**Comment by 54ayao** [comment]
好，知道了，我去发版处理一下

**Comment by 54ayao** [comment]
谢谢

**Comment by 54ayao** [comment]
![image](https://github.com/54ayao/Chinajsdelivr/assets/86733666/cf182baa-3d35-4ca3-9348-643be74884c4)
以更新
