### ISSUE TITLE
 HTTP 421

### ISSUE THREAD

**Issue by OvOCola** [54ayao/Chinajsdelivr#24]
A small number of regions display HTTP 421 status codes  display

Requested host does not match any Subject Alternative Names (SANs) on TLS certificate [feb643d6e9d9d80da547909e5986e591f7eb5b940ffec72308bbba93eb1b97d6] in use with this connection.

Visit https://docs.fastly.com/en/guides/common-400-errors#error-421-misdirected-request for more information.

**Comment by 54ayao** [comment]
Hi~ o(*￣▽￣*)ブ 

I went to check the relevant information and documentation.

This error typically occurs during an HTTPS connection when the requested hostname (also known as the target hostname or URL hostname) sent by the client does not match any of the Subject Alternative Names (SANs) on the server's TLS certificate.

A TLS certificate contains some hostnames or domains that are authorized legitimate targets of the certificate. These hostnames are listed in the Subject Alternative Names field in the certificate. When a client attempts to connect to a server, it will validate whether the Subject Alternative Names in the server's certificate include the requested hostname.



If the requested hostname is not present in the list of Subject Alternative Names in the certificate, the client will refuse the connection and display the aforementioned error message. This is typically to prevent man-in-the-middle attacks.

So my feeling is that it should be...

Checked the configuration file, Hong Kong China is among the 30 IPs in the CDN source of Jsdelivr. Fastly has made some changes to the nodes of Jsdelivr. I haven't made any changes here. So the 412 error was returned, which means that there is no such configuration information on the node.  I will run the script again to filter out the nodes and thank you for your feedback.

**Comment by 54ayao** [comment]
Just checked the platform data, and the 412 error code ranked first in the error code list, and the overall status code ranked fourth.
![image](https://github.com/54ayao/Chinajsdelivr/assets/86733666/e83919e6-1374-47ec-a755-a79c5da10ccd)
If there are no unexpected issues, it should be possible to fix it before 10:00:00 Beijing time on October 11th, 2023.

**Comment by 54ayao** [comment]
Resolved. Thank you very much for your feedback.

**Comment by 54ayao** [comment]
Wait for about 2 hours to complete the DNS update.
