### ISSUE TITLE
重定向链接会多生成一个“/”

### ISSUE THREAD

**Issue by cooliceycold** [54ayao/Chinajsdelivr#25]
比如https://jsd.cdn.zzko.cn/npm/alist-web@latest/dist/
重定向过去是这个https://jsd.cdn.gitkf.com//npm/alist-web@latest/dist/

**Comment by 54ayao** [comment]
好，稍等十分钟

**Comment by 54ayao** [comment]
应该没问题了，再看看。

**Comment by cooliceycold** [comment]
链接正常 但是似乎不允许跨域请求

**Comment by 54ayao** [comment]
不会吧我再看看

**Comment by cooliceycold** [comment]
有No'Access-Control-Allow-Origin' header报错

**Comment by 54ayao** [comment]
![mmexport1699336121348.png](https://github.com/54ayao/Chinajsdelivr/assets/86733666/f8ced15b-3152-440b-88b7-01971ee2d38e)

我这里没看到问题

**Comment by 54ayao** [comment]
![mmexport1699336290097.jpg](https://github.com/54ayao/Chinajsdelivr/assets/86733666/41757ea1-6f0e-45d6-ae88-b25dba3b22f1)
方便提供一下域名吗？

**Comment by 54ayao** [comment]
或者是 eo-log

**Comment by 54ayao** [comment]
以尝试在302请求头增加了 
Access-Control-Allow-Origin *
下发到全网大概需要五分钟左右。

**Comment by cooliceycold** [comment]
好了  正常了
